Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                       count    min threads    max threads
----------------------  -------  -------------  -------------
all                           1              1              1
move_and_rename_fastqs        4              1              1
total                         5              1              1

Resources before job selection: {'_cores': 4, '_nodes': 9223372036854775807}
Ready jobs (4):
	move_and_rename_fastqs
	move_and_rename_fastqs
	move_and_rename_fastqs
	move_and_rename_fastqs
Select jobs to execute...
Selected jobs (4):
	move_and_rename_fastqs
	move_and_rename_fastqs
	move_and_rename_fastqs
	move_and_rename_fastqs
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775803}

[Sat May 21 13:55:06 2022]
rule move_and_rename_fastqs:
    output: test/fastq/lib002_R1.fastq.gz
    jobid: 2
    wildcards: library_id=lib002
    resources: tmpdir=/tmp


        ln -sf test/inputs/atac2_R1.fastq.gz test/fastq/lib002_R1.fastq.gz
        

[Sat May 21 13:55:06 2022]
rule move_and_rename_fastqs:
    output: test/fastq/lib004_R1.fastq.gz
    jobid: 4
    wildcards: library_id=lib004
    resources: tmpdir=/tmp


        ln -sf test/inputs/atac4_R1.fastq.gz test/fastq/lib004_R1.fastq.gz
        

[Sat May 21 13:55:06 2022]
rule move_and_rename_fastqs:
    output: test/fastq/lib001_R1.fastq.gz
    jobid: 1
    wildcards: library_id=lib001
    resources: tmpdir=/tmp


        ln -sf test/inputs/atac1_R1.fastq.gz test/fastq/lib001_R1.fastq.gz
        

[Sat May 21 13:55:06 2022]
rule move_and_rename_fastqs:
    output: test/fastq/lib003_R1.fastq.gz
    jobid: 3
    wildcards: library_id=lib003
    resources: tmpdir=/tmp


        ln -sf test/inputs/atac3_R1.fastq.gz test/fastq/lib003_R1.fastq.gz
        
Waiting at most 5 seconds for missing files.
Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 493, in check_and_touch_output
    wait_for_files(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/io.py", line 825, in wait_for_files
    raise IOError(
OSError: Missing files after 5 seconds:
test/fastq/lib002_R1.fastq.gz

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 529, in _finish_jobs
    self.get_executor(job).handle_job_success(job)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 608, in handle_job_success
    super().handle_job_success(job)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 265, in handle_job_success
    job.postprocess(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/jobs.py", line 1011, in postprocess
    self.dag.check_and_touch_output(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 500, in check_and_touch_output
    raise MissingOutputException(
snakemake.exceptions.MissingOutputException: Job Missing files after 5 seconds:
test/fastq/lib002_R1.fastq.gz
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 2 completed successfully, but some output files are missing. 2

MissingOutputException in line 22 of /home/jeszyman/repos/atac-seq/workflow/tmp2.smk:
Job Missing files after 5 seconds:
test/fastq/lib002_R1.fastq.gz
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 2 completed successfully, but some output files are missing. 2
Waiting at most 5 seconds for missing files.
Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 493, in check_and_touch_output
    wait_for_files(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/io.py", line 825, in wait_for_files
    raise IOError(
OSError: Missing files after 5 seconds:
test/fastq/lib002_R1.fastq.gz

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 529, in _finish_jobs
    self.get_executor(job).handle_job_success(job)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 608, in handle_job_success
    super().handle_job_success(job)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 265, in handle_job_success
    job.postprocess(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/jobs.py", line 1011, in postprocess
    self.dag.check_and_touch_output(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 500, in check_and_touch_output
    raise MissingOutputException(
snakemake.exceptions.MissingOutputException: Job Missing files after 5 seconds:
test/fastq/lib002_R1.fastq.gz
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 2 completed successfully, but some output files are missing. 2

MissingOutputException in line 22 of /home/jeszyman/repos/atac-seq/workflow/tmp2.smk:
Job Missing files after 5 seconds:
test/fastq/lib002_R1.fastq.gz
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 2 completed successfully, but some output files are missing. 2
Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 493, in check_and_touch_output
    wait_for_files(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/io.py", line 825, in wait_for_files
    raise IOError(
OSError: Missing files after 5 seconds:
test/fastq/lib002_R1.fastq.gz

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 529, in _finish_jobs
    self.get_executor(job).handle_job_success(job)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 608, in handle_job_success
    super().handle_job_success(job)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 265, in handle_job_success
    job.postprocess(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/jobs.py", line 1011, in postprocess
    self.dag.check_and_touch_output(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 500, in check_and_touch_output
    raise MissingOutputException(
snakemake.exceptions.MissingOutputException: Job Missing files after 5 seconds:
test/fastq/lib002_R1.fastq.gz
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 2 completed successfully, but some output files are missing. 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1069, in execute
    success = self.scheduler.schedule()
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 440, in schedule
    self._finish_jobs()
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 534, in _finish_jobs
    self._handle_error(job)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/scheduler.py", line 615, in _handle_error
    self.running.remove(job)
KeyError: move_and_rename_fastqs

unlocking
removing lock
removing lock
removed all locks
